# Change these first 
owner: sahal # Your GitHub organization or username, where this repository lives
repo: cbgn-uptime # The name of this repository

delay: 2300

sites:
  - name: Naked Domain
    url: https://bikegridnow.org
    __dangerous__body_down_if_text_missing: '10% of Chicago streets prioritized for pedestrians and cyclists, created by traffic calming infrastructure and a lower speed limit to keep everyone safe.'
    expectedStatusCodes:
      - 200
  - name: Cloudflare DNS Monitoring (via Google) - Addilyn # This is a test to see if the DNS has been modified. Big problem, if so.
    url: https://dns.google/resolve?name=bikegridnow.org&type=NS
    __dangerous__body_down_if_text_missing: 'addilyn.ns.cloudflare.com.'
  - name: Cloudflare DNS Monitoring (via Google) - Ryan
    url: https://dns.google/resolve?name=bikegridnow.org&type=NS  # This is a test to see if the DNS has been modified. Big problem, if so.
    __dangerous__body_down_if_text_missing: 'ryan.ns.cloudflare.com.'
  - name: API Token Test # This is a test to see if the API token is still valid :x
    url: $APIPROVIDERURL_1
    headers: 
      - "Authorization: Bearer $APITOKEN"
      - "Content-Type: application/json"
      - "X-Requested-With: XMLHttpRequest"
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: '2025-09-08 Alerting'
  - name: API Active Test # This is a test to see if the API is "active"
    url: $APIPROVIDERURL_2
    headers: 
      - "Authorization: Bearer $APITOKEN"
      - "Content-Type: application/json"
      - "X-Requested-With: XMLHttpRequest"
    expectedStatusCodes:
      - 200
    __dangerous__body_down_if_text_missing: $APIMATCH
      
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /cbgn-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CBGN Upptime Monitoring
  introTitle: "Checking CBGN endpoints every 15 minutes."
  introMessage: This uses [Upptime](https://github.com/upptime/upptime) and Github Actions.
  navbar:
    - title: Status
      href: https://sahal.github.io/cbgn-uptime/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

workflowSchedule:
  graphs: "21 0 * * *"
  responseTime: "22 23 * * *"
  staticSite: "23 1 * * *"
  summary: "24 0 * * *"
  updateTemplate: "25 0 * * *"
  updates: "26 3 * * *"
  uptime: "*/15 * * * *"

user-agent: sahal
